### ISSUE TITLE
Weekly stats counter not right on Sunday

### ISSUE THREAD

**Issue by Thricehappy** [Thricehappy/EveScoutRescue#118]
"Current week" stats are from Sunday to Saturday. On Sunday, they get wonky. Need to fix this.

**Comment by bikerunner** [comment]
Can be fixed with DB structure rework ( #92 ).

* should this by a fixed date/time combination
* should the activities get a flag (set by payout maybe) to relate to the week

**Comment by Thricehappy** [comment]
I think this is just due to a poorly written query, nothing more. It works well enough, but now there are people asking about why it isn't right, so it needs to be fixed! :-)

**Comment by Thricehappy** [comment]
I think this is finally fixed. Hooray!
