### ISSUE TITLE
Don't require "J" to be typed in for wormhole system name

### ISSUE THREAD

**Issue by Thricehappy** [Thricehappy/EveScoutRescue#12]
Bill Kills:
Could we drop the "J" in the search boxes for ESRC? Or pre-fill it... or silently add it for lazy bastards like me.

**Comment by bikerunner** [comment]
Is this still necessary? The Jxxxxxx is displayed in type-ahead and can be selected.

**Comment by Thricehappy** [comment]
I agree. Let's just leave this alone for the moment. Doesn't seem to be an issue with anyone else, and even Bill said this was working OK for him a while after he sent this original request.
