### ISSUE TITLE
Add notes without some other action

### ISSUE THREAD

**Issue by bikerunner** [Thricehappy/EveScoutRescue#128]
Request from forum: https://forums.eve-scout.com/topic/1463/esr-tech-updates-megathread/35

Add notes to a cache without a tend action should be possible.

Notes need to be separated while restructure DB.

**Comment by chigaze** [comment]
Reviewing: Current situation now that 217 is merged is Admins can add a note through edit cache, system notes are better exposed, and a note can be added but you need to tend the cache. I think the times someone would need to add a cache note with tending it are rare, non-coordinators have to be in system to tend the cache at all. The remaining edge cases can be handled by the pilot contacting a coordinator.

**Comment by adeadparrot** [comment]
Agree with Igaze. Closing
