### ISSUE TITLE
Lookup chain information from Tripwire

### ISSUE THREAD

**Issue by bikerunner** [Thricehappy/EveScoutRescue#142]
There exists code (https://github.com/farshield/shortcircuit ; python) which searches chain information from tripwire.

We should adapt this to:
- check known connections for caches which are about to expire
- check frequently (2 times a day?) for active SAR requests to rescure the lost pilots

**Comment by bikerunner** [comment]
Did not get a response from D.M. after last question. It seems that TW is not used by all pilots. Can we use internal connection data?

**Comment by Thricehappy** [comment]
This is one we need to discuss with Parrot.

**Comment by chigaze** [comment]
Given that ShortCircuit has not been updated in ages and I think does not work the updated ESI we definitely could not search TW for this data. We also do have a number of active pilots who do not use TW for a variety of reason including, ironically, that Allison does everything they need. 

I'm also not sure if such a notification would be needed as if a a system is in the your chain then someone was there in the last 24 hours. While this does not guarantee the cache was tended it does mean it is far more likely. 

My inclination would be to close this. If it comes up again later with a good argument in its favour then a new issue could be opened.

**Comment by adeadparrot** [comment]
Agree with Igaze. Closing
