### ISSUE TITLE
Payment opt-out interface

### ISSUE THREAD

**Issue by Thricehappy** [Thricehappy/EveScoutRescue#143]
Create a way for pilots to opt out of being part of the weekly payout pool.

**Comment by bikerunner** [comment]
Does it require a separate table with pilot names who want to opt-out?
Best would be an in game option to toggle if accessible by API. This would prevent a separate data structure.

Should the OPT-OUT pilots get a notification eve-mail on each payout or at least once a week to remind?

**Comment by Thricehappy** [comment]
There are actually lots of reasons to have a table of pilots, both for ESRC and SAR. So, it will happen, but not until after the db restructure.

**Comment by chigaze** [comment]
Review: I've had a couple of requests for this and it would be a nice enhancement. Currently I don't opt-out people from payouts as it would be more work on the payouts for me if I have to manage it manually.

**Comment by chigaze** [comment]
I have had a number of requests to opt-out of the payouts but as it would take me longer to manually manage that I don't. If there were a way I could flag pilots to opt out then that could make them happy and save me time.
One thing would be is the opt-out should only be for ESRC and not the SAR payouts.

**Comment by Thricehappy** [comment]
Ready for testing in production. Let me know if any tweaks are needed, @chigaze

**Comment by Thricehappy** [comment]
All good, per Igaze.
