### ISSUE TITLE
ESRC: User session Timeouts too fast w/o Allison

### ISSUE THREAD

**Issue by Thricehappy** [Thricehappy/EveScoutRescue#144]
We need to come up with a way to extend the session to about 2-3 hours for pilots who do not fly with Allison. The 20-minute timeout means you have to log in almost every single time you sow or tend a cache. Annoying!

We've already tried doing this programmatically in PHP and by adding in our own php.ini. Neither seems to be working.

**Comment by bikerunner** [comment]
Is there some validation of the user session with CCP login server while make a requests? Can the timeout be related to a CCP session timeout?

**Comment by Thricehappy** [comment]
Yes, if you have a scope declared when you auth. Because ESRC does not have any scope, we cannot refresh the auth token like Allison can. So, this is a non-issue for pilots who fly with Allison. Those who do not (like Eratos) have to re-login in every 20 minutes. Ugh!

**Comment by bikerunner** [comment]
I leave Allision sometimes open turned off. This is sufficient to keep the session active. Copilot seems to do some requests in background anyways.

So workaround would be: Start copilot and turn it off. The session stay active.

**Comment by Thricehappy** [comment]
Closed because Allison is now required to do ESR work
