### ISSUE TITLE
ESRC: Agent record sets recently tended flag

### ISSUE THREAD

**Issue by Thricehappy** [Thricehappy/EveScoutRescue#146]
Adding an agent record sets the recently tended flag on a cache but it should not. See, for example, J215736

**Comment by bikerunner** [comment]
The "lastupdated" column is set because the note is changed.
The "expiresOn" column is not updated which seems to be ok.

Expiration should rely on the "expiresOn" I think or I do not see the issue.

**Comment by Thricehappy** [comment]
Tested as resolved after latest PR. Thanks, @bikerunner !
