### ISSUE TITLE
Change Page/Tab title to mark active SAR request

### ISSUE THREAD

**Issue by bikerunner** [Thricehappy/EveScoutRescue#148]
Today I entered a system with an active SAR request. I heard some longer speech from Allison but did not note right now. I notived it just before I jump out of the system.

Can we add a small visual change to the title of the browser TAB?

Currently: "Jxxxxxx:Recently Tended"
Changed: "(!)Jxxxxxx:Recently Tended"

This may give a visual hint.

**Comment by Thricehappy** [comment]
@adeadparrot controls the state of the browser tab from Allison, so this would be for him to do.

We should probably build this into ESRC for those who fly w/o Allison, but this is something I am not sure how to do. Add it to the list! :-)

**Comment by adeadparrot** [comment]
closing in favor of #294
