### ISSUE TITLE
Separate rescue reports out from ESRC/SAR interfaces

### ISSUE THREAD

**Issue by Thricehappy** [Thricehappy/EveScoutRescue#161]
We need to handle the reporting of rescues independently of the ESRC and SAR interfaces. This new "rescue reporting" interface can be a third tab across the top of the main overview page.

This will help lessen confusion over whether a certain rescue is ESRC or SAR and will make reporting on confirmed rescues easier.

This should be done after the DB Restructure just to keep things simple. This may require some slight db modifications of its own, but I don't want to slow down the DB Restructure project any.

**Comment by bikerunner** [comment]
Can you already define which data is entered, how the data should be stored and how to process the reports? Just to see if this already influence the DB structure in general.

**Comment by Thricehappy** [comment]
I'll take a look at providing more detail soon.

**Comment by Thricehappy** [comment]
Done!
