### ISSUE TITLE
full timestamp on SAR pages for coordinators

### ISSUE THREAD

**Issue by adeadparrot** [Thricehappy/EveScoutRescue#175]
SAR feature requeset: Can we see the full timestamp (EVE time) of when a SAR was started? Trying to figure out when someone was podded relative to when the request was made.

**Comment by chigaze** [comment]
I would give this issue some priority. I still look at timestamps on SAR requests and have to think if they're in EVE or my local time. Having them clearly marked as EVE time would be great, particularly on the "rescueoverview" page.
