### ISSUE TITLE
ESRC: Add arabic number option for planets

### ISSUE THREAD

**Issue by Thricehappy** [Thricehappy/EveScoutRescue#189]
Can we get an option to change planets to numbers instead of roman numerals?
Because my keyboard doesn't type in roman numerals.
https://forums.eve-scout.com/post/39013

**Comment by adeadparrot** [comment]
I just don't see this as an issue.  No keyboard "types" roman numerals. And the entries are in a drop-down menu, which eliminates the need to type Roman numerals in the first place.
