### ISSUE TITLE
Add statics to WH info on system-specific display

### ISSUE THREAD

**Issue by Thricehappy** [Thricehappy/EveScoutRescue#193]
Can we get the system's Statics listed on the detail page as well? For example, pulling up the page for a search in J222914 would show it's a c1 with a Nullsec connection
- Triffton Ambraelle

**Comment by Thricehappy** [comment]
Merge [mapWormholes] from dev into [wh_systems] table so we can display static connections for each WH.

**Comment by Klensor** [comment]
duplicate of #212
