### ISSUE TITLE
Eliminate ESR web site login

### ISSUE THREAD

**Issue by Thricehappy** [Thricehappy/EveScoutRescue#196]
Since all ESR stuff requires the use of Allison, remove login option from web site. Having two separate logins is confusing.

(Maybe retain separate login to web site only for admins and/or ESR Coordinators?)

**Comment by adeadparrot** [comment]
There are cases where you should be able to log in without Allison, Mostly for coordinators and other admin related duties. Suggest no change.

**Comment by adeadparrot** [comment]
Closing this to get it off the table.
Being able to access stand alone pages without Allison is very helpful for pure administrative functions (like payouts for example), as well as for testing.
