### ISSUE TITLE
Store all dates in db as UTC

### ISSUE THREAD

**Issue by Thricehappy** [Thricehappy/EveScoutRescue#197]
Right now, we convert some dates to UTC before inserting, and we convert some dates to UTS when displaying. This is inconsistent and confusing.

Instead, store all dates in db in UTC and then there is no need to convert ion display.

**Comment by Thricehappy** [comment]
ESRC data seems to be good now. All dates are being inserted as UTC.
SAR is structured differently, but also datetime is less critical for those records.

Will keep an eye on it for now and continue to tackle as needed. But this is mostly good for now. Setting to Low Prio.

**Comment by adeadparrot** [comment]
PR#299 should have covered this
