### ISSUE TITLE
SAR: Let stranded pilot open request

### ISSUE THREAD

**Issue by Thricehappy** [Thricehappy/EveScoutRescue#204]
Create interface for stranded pilot to open their own SAR request.
Link to this will be given to them by a 911 Operator.
Link will include tracking for which Operator helped them out.
Form should include areas to answer all questions we typically ask in the SAR Flowchart.

Work with 911 Operators to design flow.
Russian version?

**Comment by bikerunner** [comment]
Should this be assigned to the 911 repo somehow? Not sure if this can be implemented in the ESRC code base or should be in the 911 code base?

**Comment by Thricehappy** [comment]
The vision was for the 911 form to be a full SAR form so that our 911 operators do not need to fill it all in. This may require coordination with @adeadparrot . I will leave it to you all to decide how much you want to automate. I am sure @chigaze will have input as well.

**Comment by adeadparrot** [comment]
I think this was reviewed several times within the groups, and each time it was agreed that the personal contact required for a 911 call was a major part of the content we enjoy.  Automating it would reduce our available content.
