### ISSUE TITLE
SAR: Possibly add a form field for discord name?

### ISSUE THREAD

**Issue by adeadparrot** [Thricehappy/EveScoutRescue#209]

**Comment by Klensor** [comment]
Is this useful to have as a seperate field? We can always add that info to the notes, right?

**Comment by chigaze** [comment]
I'm ambivalent on this one. While it can be recorded in the notes having a field does serve a purpose in prompting our operators to prompt for one. A whole field for that purpose feels a bit like overkill.

**Comment by chigaze** [comment]
Being handled well in the notes field.
