### ISSUE TITLE
Adding SAR system statics to Allison and SAR page

### ISSUE THREAD

**Issue by RGDarragh** [Thricehappy/EveScoutRescue#212]
Both Allison and the SAR page list out

System
Class
Opened date
Status

I'd like to know what kind of effort it would take to list System Statics as well. I think it would allow pilots to target their search a little better than we currently do.

Take the situation where a pilot is lost in a C1. Currently I'd check Anoik.is to find that the C1 has a J244 low sec static and then head out to low sec and start looking for K162s leading to Unknown space. Or we're looking for a C5 with a C2 static. At least if I'm in a C2 and have a K162 leading to Dangerous space I know there's a chance to find the system.

**Comment by Klensor** [comment]
I'm sure I read somewhere that the statics are based on the wh constellation. Is that true? Can we otherwise mine the list from the static data?

**Comment by Thricehappy** [comment]
Statics for a given system are always the same. We should definitely have access to this info.

**Comment by chigaze** [comment]
List here, not sure where we can get it in a better form for our use. http://anoik.is/systems

**Comment by Klensor** [comment]
Thanks @chigaze - that site has some nice js wizardry, and all the data sits in a .json file we can use to populate some new tables. I'll get on it...

**Comment by Thricehappy** [comment]
Closed as part of PR #237 and #228
