### ISSUE TITLE
Limit available planets in 'Sow cache' view

### ISSUE THREAD

**Issue by bikerunner** [Thricehappy/EveScoutRescue#215]
*Change:*
* the number of planets of a WH should be known and constant
* add this number to the WH table in database
* limit the number of listed planets in location and align lists to this number

*Advantage:*
* not possible to select wrong planets
* less listed planets may result in faster view processing

**Comment by Thricehappy** [comment]
Can we confirm this is closed now?

**Comment by bikerunner** [comment]
Can reopen if someone complains. Or create a new issue if something not working. Expect no issues at the moment.
