### ISSUE TITLE
New SAR form has incorrect instructions for entering pilot name

### ISSUE THREAD

**Issue by chigaze** [Thricehappy/EveScoutRescue#225]
The form currently says: 
"Stranded Pilot
    Enter as "Pilot Name (Contact Name)" if an intermediate contact is involved."

We do not include contact name in brackets anymore as that breaks the eveWho link. 

Edit to say:

"Stranded Pilot
   Other contact names, if any, should be entered in Notes"

**Comment by Klensor** [comment]
Closing as PR merged
