### ISSUE TITLE
esrcoordadmin.php - Stop the insanity

### ISSUE THREAD

**Issue by adeadparrot** [Thricehappy/EveScoutRescue#244]
esrcoordadmin.php does two round trips to the database for every single row of the table showing past SAR requests. And the requests are all redundant.
This needs to be rewritten.

**Comment by bikerunner** [comment]
BTW.: It's not just a roundtrip. It opens a total of 3 DB connection and two are fast opened and closed again.

**Comment by adeadparrot** [comment]
It looks like this could all be done in a single query. If we send the character name of the requester to the query...

**Comment by Thricehappy** [comment]
Hey, take it easy! I through this together in an afternoon and it only gets used by the ESR division admin maybe once or twice a week. :-)

But, sure, it can be optimized at this point.

**Comment by chigaze** [comment]
Seven seconds load time for me now. :)

What I'd really like, though, is a way to edit the Locator and Rescue Pilots but that should probably be another request... may even be on already, I should check.
