### ISSUE TITLE
LOG IN with EVE Online button does not respond to taps on iOS

### ISSUE THREAD

**Issue by chigaze** [Thricehappy/EveScoutRescue#248]

**Comment by chigaze** [comment]
Also on Android. From Triffton: "Not sure if it's me or a broader issue, but the login button on ESR website isn't clickable for me. Navigating to any page behind Auth requirement works just fine, been navigating to ESR overview manually as a workaround for a couple days now. Chrome on Android, everything is updated to current version."

**Comment by adeadparrot** [comment]
fixed in Oct 26 update
