### ISSUE TITLE
Ability to Edit the Rescue Pilots on a SAR

### ISSUE THREAD

**Issue by chigaze** [Thricehappy/EveScoutRescue#254]
There are occasions where someone is omitted from the rescue pilot list but should be included. The most common is a locator who does help with the rescue but does not exit and re-enter the system to get themselves on the rescue pilot list. This happened recently when the locator helped with the rescue and the wormhole collapsed behind them.

**Comment by adeadparrot** [comment]
Issue #190 related to this - and should be in place first.

**Comment by chigaze** [comment]
Given how often I have to ask Thrice to manually edit this I believe this should be a fairly high priority. While the recheck function has lowered the numbers it is still the case that pilots forget and we have rescues with no rescue pilots.

**Comment by Thricehappy** [comment]
Ready for testing on dev. http://dev.evescoutrescue.com/esrc/rescueoverview.php?sys=J100001 - for example.

**Comment by chigaze** [comment]
Tested and appears to work. Would it be possible to add a locator as well. Again rarely forgotten these days with the recheck ability however still would save bothering Thrice now and then. :)

Finally, and perhaps not necessary, should there be functionality to remove a pilot. Every now and then, last week for instance, a pilot is included on the rescuer list who just flew through the system by chance. Not a huge deal so maybe not worth the effort. As I can't tell I end up paying them up and/or giving them a medal.

**Comment by Thricehappy** [comment]
Added function add/update a locator. If you pick a new name when one is present, it will overwrite the current one.
Added function to remove rescue agents. Just click on the red "X"! There is no warning, but you can add them right back if you remove erroneously. No big deal.

Let me know if further changes are needed.

**Comment by chigaze** [comment]
Please restrict to only the Admin role on evescoutrescue.com

**Comment by Thricehappy** [comment]
New functionality to add/update Locator and Add/Remove Rescue pilots has been restricted to Admins only. Tested and deployed to DEV. Please confirm and I will push all changes to production.
