### ISSUE TITLE
Convert POSTs on search.php to GETs

### ISSUE THREAD

**Issue by Thricehappy** [Thricehappy/EveScoutRescue#26]
- search.php should always pass form submits as GETs

**Comment by bikerunner** [comment]
What is the background of this issue?

**Comment by Thricehappy** [comment]
I am handling search form submits as $_POST but also pass in search parameters on the querystring via $_GET. I had special handling in there to set a variable to the value of either the $_POST or the $_GET search parameter. I thought making everything to $_GET would streamline the code a bit.

Maybe you have already taken care of this, though, by switching my $_GETs and $_POSTs to $_REQUEST? Let me know what you think!

**Comment by bikerunner** [comment]
This seems to be solved.
