### ISSUE TITLE
TEND button: Cache position same as last

### ISSUE THREAD

**Issue by adeadparrot** [Thricehappy/EveScoutRescue#274]
when using the new bookmarks, have a button to duplicate previous info so pilot does not  have to reenter everything manually... password too??

**Comment by okuRaku** [comment]
I believe this would be a "sow" operation (title says "tend") - the idea is to sow a new cache using the same details as before (because bookmark) but without having to retype.  Password can be new or old, shouldn't matter I believe.

**Comment by adeadparrot** [comment]
Closed with PR#292
