### ISSUE TITLE
Ability to mark a cache as unaligned rather than having a target and align planet.

### ISSUE THREAD

**Issue by chigaze** [Thricehappy/EveScoutRescue#282]
For the few systems where the locals regularly destroy the caches but have not made a no sow request we would like to try placing the caches in unaligned position accessible only by bookmark. When sowing we need a way to indicate this.  I'm not sure how the validation works but if possible just set the target to unaligned and leave the align planet blank would be good. Otherwise the ability to set each to unaligned would work as well.

**Comment by adeadparrot** [comment]
Closed with PR#292
