### ISSUE TITLE
Rescue Cache Name Change

### ISSUE THREAD

**Issue by chigaze** [Thricehappy/EveScoutRescue#289]
Due to a change in allowed characters for names, question marks are no longer allowed in container names. We'll need a change to the copy text for naming rescue caches. Replace the question mark with a period. The question mark is now an illegal character.

**Comment by chigaze** [comment]
Revision. After some discussion about grammar please change the text to:

"EvE-Scout Rescue Cache - If you are stranded in this wormhole, you can request help in the EvE-Scout channel."

**Comment by adeadparrot** [comment]
Done
