### ISSUE TITLE
Tripwire note automation

### ISSUE THREAD

**Issue by Thricehappy** [Thricehappy/EveScoutRescue#3]
* Every time a new cache is sown, we need to automatically enter a note into TW.
* Every time a cache is expired, either manually by a tender or automatically by the cron job (due to expiration date being reached), we need to remove that same note from TW.

**Comment by Thricehappy** [comment]
- Emailed Daimian Mercer re: this project
- Prepped relevant files for new code.

**Comment by Thricehappy** [comment]
With Co-Pilot in place, do we still need this?

**Comment by bikerunner** [comment]
I see the TW notes as a public information. But this should not be necessary. Lost pilots need to use the Eve-Scout channel for more info all time. I vote to close this issue.

**Comment by Thricehappy** [comment]
That's how I'm feeling about it, too. I also think Co-Pilot is superior in every way to the idea of TW notes you have to go and look at.
