### ISSUE TITLE
Remove the Coordinator exclusion on Locator payouts

### ISSUE THREAD

**Issue by chigaze** [Thricehappy/EveScoutRescue#324]
Have discussed with the other ESR Managers and we agree this currently outdated and can be handled other ways. Frankly most locates are by operators now.

**Comment by Thricehappy** [comment]
So, to confirm, you want to remove this exclusion and pay Locators the same across the board, regardless of whether Locator is an ESR Coordinator?

Once you confirm, I'll take a look. Probably will be next week before I can get to it.

**Comment by chigaze** [comment]
That is correct. 

We are also looking at changing the first day payout because so many rescues are now instant rescues because we have chains to the systems. The amount is a bit high for the volume. Will get back to you on that in another issue as we are looking at payouts in general.

**Comment by Thricehappy** [comment]
Rolled out and tested.
