### ISSUE TITLE
ESR Admin is showing a blank page (no source)

### ISSUE THREAD

**Issue by chigaze** [Thricehappy/EveScoutRescue#325]
https://evescoutrescue.com/esrc/esrcoordadmin.php

Safari 13.1.2

Source inspector shows: 

<html>
<head></head>
<body></body>
<html>

php file shows empty although there is a js file. 
<img width="567" alt="Screen Shot 2020-08-14 at 7 33 23 AM" src="https://user-images.githubusercontent.com/2007040/90254762-7dca5600-de00-11ea-9ddb-e2296f4ce95c.png">

**Comment by Thricehappy** [comment]
Replaced missing file removed as part of recent refactoring rollout. tested and working on production.

I'll leave the file in place until refactoring work is complete.
