### ISSUE TITLE
Cache stats are not showing past August 12th, 2020

### ISSUE THREAD

**Issue by chigaze** [Thricehappy/EveScoutRescue#327]
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/2007040/90336487-670b3700-df99-11ea-9bd9-577c071be9b4.png">

**Comment by Thricehappy** [comment]
Missing data has been entered. An estimate was made for active cache count each day data was missing.

This should be resolved, but I'll keep an eye on it this week to make sure.

**Comment by Thricehappy** [comment]
Pages that cron calls are working fine, but cron does not seem to be firing correctly. I have updated and will check again tomorrow to make sure it is working again as expected.

**Comment by Thricehappy** [comment]
Confirmed that all is working well now.
