### ISSUE TITLE
 Remove agent actions from ESRC payouts and expand dispatch payouts to include all dispatches including "Rescued - ESRC".

### ISSUE THREAD

**Issue by chigaze** [Thricehappy/EveScoutRescue#328]
Currently if a dispatcher conducts an agent rescue that is counted in the ESRC payouts but not as a dispatch. In general this means a lower payout, as cache payouts are lower than dispatch ones, and it makes compiling the list of dispatchers each week longer as two different lists need to be consulted.

**Comment by Thricehappy** [comment]
Rolled out and tested. ESRC list decreased slightly and SAR Dispatch list increased by a lot! it more than doubled, due to counting ESRC Rescues here now.
