### ISSUE TITLE
Editing the Locator or Rescue Pilot on a closed SAR changes the rescue date

### ISSUE THREAD

**Issue by chigaze** [Thricehappy/EveScoutRescue#331]
When using the ESR Manager ability to edit locator or rescue pilots for a SAR the reported Rescue Date in the Admin Payouts interface shows the timestamp of when the record was edited rather than when the SAR was closed.

Of note: The date filter works as expected in the payouts interface, only show rescues actually closed in the range rather those whose reported rescue date is in the range. 

Replicate: 

Edit the locator or rescue pilot for a SAR. 
In payouts for SAR Locate/Rescue set a date range that includes the original rescue date for the SAR you edited.
Sort by Rescue Date, the one you edited should be on top (see attached image of the 30 or so I edited today)
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/2007040/90686057-004f7d00-e228-11ea-85ea-3b5ea3777f15.png">
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/2007040/90686094-13624d00-e228-11ea-88e4-dcec5ec9c14c.png">

**Comment by Thricehappy** [comment]
As far as I can tell, this was only occurring when Locator was edited. But it has now been fixed and should no longer be an issue.
