### ISSUE TITLE
Updates to SAR Payout Formula

### ISSUE THREAD

**Issue by chigaze** [Thricehappy/EveScoutRescue#332]
Changes to be made to the base SAR payout formula:

System Class:
C14-C18 as C6

Base payout for 0 day rescue, change from 50m ISK to 20m ISK.

I modelled the changes in the SAR - Payouts Planner sheet. See the second tab: Working Revision.

**Comment by Thricehappy** [comment]
This is in production now. Please let me know if anything is not being calculated correctly. Thanks!
