### ISSUE TITLE
Data errors on ESR Admin - Medals - SAR

### ISSUE THREAD

**Issue by CCrinkle** [Thricehappy/EveScoutRescue#333]
Under the above section, pilots who have left the corp a long time ago ( a year or more ) are shown as qualifying for SAR Medals in the last week . 
![image](https://user-images.githubusercontent.com/70095067/90976593-419ca100-e536-11ea-9919-e431c2e78900.png)

**Comment by Thricehappy** [comment]
How often will it be that you go in and update old SARs with new rescue pilots?
If this last round was mostly a one-time thing, than I think we should just leave #333 alone and let those updated records slowly filter out of the medals listing.
There is only date to check for awarding medals to recue pilots, the date of when they were added to the rescue. This is only an issue for medals when they are added way after the fact, as in this case.
I can go in and change dates on all of these you updated recently, if needed, although it will be a bit painstaking to find them all. Let me know what you all think.

**Comment by Thricehappy** [comment]
After further convo with Igaze, we will not fix this. It's a one-time issue, we hope.
