### ISSUE TITLE
Endpoint for the best storm chaser

### ISSUE THREAD

**Issue by zap2zero** [Thricehappy/EveScoutRescue#345]
I would like to have an endpoint of yesterdays best storm chaser. The returned pilot should have the most storms reported from either
11:00am yesterday - 11:00am today (if its after 11:00am) or
11:00am two days ago - 11:00am yesterday (if its not yet 11:00am).
All times must be GMT ofc.

The returned data should look like
`{"uid":1234,"Pilot":"Captain Top Secret","Actions":7}`

The returned content type should be `application/json`

**Comment by Thricehappy** [comment]
Complete: https://evescoutrescue.com/esrc/stats_top_stormchaser.php
