### ISSUE TITLE
Storm Tracker Enhancements

### ISSUE THREAD

**Issue by KatiaSae** [Thricehappy/EveScoutRescue#349]
1) Table instead of ticker scroll limited to 10 entries sorted by update, most recent first. Column headings: Region, System, Storm Type, Reported by, Last Report. [See this post](https://forums.eve-scout.com/topic/8378/storm-tracking-where-to-go-from-here/18) for an example. 

2) Allow storm type "Unknown"

3) Change expiration to 36 hours

4) Allow duplicate entries to be updated after 12 hours, refresh the expiration time

**Comment by KatiaSae** [comment]
Suggestion on enhancement 1 is to leave ticker scroll, but add a link to table.

**Comment by KatiaSae** [comment]
ADP had some good thoughts on storm expiration. [Thoughts on his post?](https://forums.eve-scout.com/topic/8378/storm-tracking-where-to-go-from-here/29) Is something like that doable?

**Comment by Thricehappy** [comment]
1-3 are live in production.

I will be working on 4 as we discussed today, @KatiaSae . I'll let you know when those revisions are ready to review in dev.
