### ISSUE TITLE
 Agent actions are not marking caches as "Upkeep required"

### ISSUE THREAD

**Issue by chigaze** [Thricehappy/EveScoutRescue#354]

**Comment by Thricehappy** [comment]
Can you describe the steps to replicate this issue? I just tested on dev and it seems to work fine: http://dev.evescoutrescue.com/esrc/search.php?sys=J230049

**Comment by chigaze** [comment]
I saw it on J160941, unfortunately someone has been through and tended it today and was sure I had seen it happen before. Spot checking back and it looks like it's working. Might be an edge case of particular conditions. I would say close this for now and I'll keep an eye out to see if it happens again. :/

**Comment by Thricehappy** [comment]
Fair enough.
