### ISSUE TITLE
Storm Tracker Update Issue & Feature Request

### ISSUE THREAD

**Issue by KatiaSae** [Thricehappy/EveScoutRescue#355]
1) Issue: Looks like when the same system is updated, the 12 timer gets reset. We should not allow duplicate updates to prevent this from happening.

2) Feature: Is it possible to replace the dropdown with a name sensitive search. ie. as you enter the system name it filters possible selections to choose from.

**Comment by Thricehappy** [comment]
Can you provide steps to replicate the issue you are reporting in the issue your report? I am not clear what the problem is.

As for the typeahead feature you request, I will look at implementing something like this on Thursday.

**Comment by KatiaSae** [comment]
It's pretty straight forward. When the "New Report" button is available for a given storm, click on it, enter the same system the storm is already in. This creates a duplicate history entry for that storm/system which then resets the 12 hour timer. Preventing a duplicate entry should prevent that from happening. I cleaned up the entries from a few days ago, so you won't see them in the history unless you have an audit of deletes or something.

**Comment by Thricehappy** [comment]
I thought you wanted duplicate entries to be permitted, so we could confirm a storm had stayed in the same system. If we don't allow duplicates, we won't know if the storm just hasn't moved or just hasn't been updated in a while.
So, it is working as intended right now.
