### ISSUE TITLE
Stats on prior caches

### ISSUE THREAD

**Issue by Thricehappy** [Thricehappy/EveScoutRescue#36]
For systems that have had caches sown previously, display relevant stats (duration, who sowed, where, etc.)

Maybe combine with edit interface requested in #30 ?

**Comment by bikerunner** [comment]
Is this related to #61 ? Can these issues be combined?

**Comment by Thricehappy** [comment]
Yep. Let's make this admin-only for now, unless you think seeing the full history of caches in a system would be helpful (and not confusing!) to all rescue pilots.

**Comment by Thricehappy** [comment]
I snuck this into production today. Looks pretty good, I think.
