### ISSUE TITLE
Storm Tracker - Feature Request Storm Effects

### ISSUE THREAD

**Issue by KatiaSae** [Thricehappy/EveScoutRescue#365]
We had a request from outside SC! Woot, someone is actually using the storm tracker. ;) Here's their request: "Hey, just a feature request for the EVE Scout Storm Tracker page.  Could the crew put the list of storm effects in a chart below the locations table?  I can never remember which storm does what."

Here's a link to the effects, maybe we can summarize on our page somehow. https://wiki.eveuniversity.org/Metaliminal_Storms

**Comment by Thricehappy** [comment]
If someone makes this dead simple for me by creating the chart/table we want to display, I can get it on the site. I don't need it in HTML or anything, just sketched out so I know what the content is going to be. I don't have time to create the content myself. Thanks!

**Comment by KatiaSae** [comment]
Here's a link to a table of the effects https://docs.google.com/spreadsheets/d/1xK6QJi9sgUfsWlg2N4tojmkL41bSYJ0EcO_jD4-evuI/edit?usp=sharing

**Comment by Thricehappy** [comment]
I have requested access to that sheet, but I still cannot view it. Stalled until I have access. Please advise.
