### ISSUE TITLE
Move db backups to Google Drive

### ISSUE THREAD

**Issue by Thricehappy** [Thricehappy/EveScoutRescue#4]
Create a script to auto-move db backups to Google Drive account

**Comment by Thricehappy** [comment]
So, I could build this:
http://www.matthewhipkin.co.uk/codelib/automatically-backing-up-your-web-server-files-to-googledrive-with-php/

Or I could buy this:
https://mysqlbackupftp.com/features/

Have to think about this later.

**Comment by bikerunner** [comment]
Is this not possible with a simple mysql command line export tool and a small cron job? This is more a server administration task than development I think.

**Comment by Thricehappy** [comment]
I'm using a third-party tool for cron, because I am not sure how to set that up on my web host. Same with db backup -- I can't get mysqldump to work from the command line.

I am sure these are limitations of my knowledge more than anything. So I have found third-party tools to help me work around my ignorance.

Is it time to add a sysadmin to our team? :-)

**Comment by Thricehappy** [comment]
Once #20 is compete, I'd still like to look into an automated way to copy most recent db backup to Google Drive. I'd feel better knowing I have copies of these that are not on the web server. Just in case. LOW priority, though.

**Comment by bikerunner** [comment]
Can something like this work for this: https://github.com/odeke-em/drive
There may be some different implementations.

**Comment by Thricehappy** [comment]
Looks really good. Except I don't know what GO is. :-/

**Comment by Thricehappy** [comment]
I'm just going to handle this manually for now.
