### ISSUE TITLE
Simplify search.php

### ISSUE THREAD

**Issue by bikerunner** [Thricehappy/EveScoutRescue#43]
Tasks:
- remove query code from (mostly) static html page
- prepare a leader board class
- prepare a cache status class

Status: Already in progress

**Comment by Thricehappy** [comment]
We should also remove the line on search.php that reads: "If a system is not listed, no active cache is present." Since all systems are listed now, that no longer applies and is just confusing.

**Comment by bikerunner** [comment]
Yes, it's in my focus and will be part of the change. :D
 

Gesendet: Donnerstag, 20. April 2017 um 14:05 Uhr
Von: Thricehappy <notifications@github.com>
An: Thricehappy/EveScoutRescue <EveScoutRescue@noreply.github.com>
Cc: bikerunner <k.m@gmx.net>, Assign <assign@noreply.github.com>
Betreff: Re: [Thricehappy/EveScoutRescue] Simplify search.php (#43)


We should also remove the line on search.php that reads: "If a system is not listed, no active cache is present." Since all systems are listed now, that no longer applies and is just confusing.
