### ISSUE TITLE
Allow data entry on J1226-0

### ISSUE THREAD

**Issue by Thricehappy** [Thricehappy/EveScoutRescue#46]
The special character in J1226-0 system name prevents it from being entered on data_entry.php. Need to create a special case to allow for this. It is the only system with a special character in its name.

**Comment by nthirtyone** [comment]
It is located in [data_entry.php:77](https://github.com/Thricehappy/EveScoutRescue/blob/master/esrc/data_entry.php#L77). It can be resolved in various ways:

- Allowing '-' in general, for possible new systems in future: `/\bJ[\d\-]{6}\b/`.
- Allowing '-' only in that single position with limited support for new systems with similar name: `/\bJ[0-9]{4}[0-9\-][0-9]\b/`.
- Allowing only that certain system to be entered: `/\bJ([0-9]{6}|1226\-0)\b/`.

**Comment by Thricehappy** [comment]
Thank you! I will get to this soon(TM). Feel free to jump in and make the change yourself if you feel like it! :-)

**Comment by Thricehappy** [comment]
I tested this locally and was not able to sow a cahe in this system. Got the error message:
"System must be in the format: J######, where # is any number."
