### ISSUE TITLE
IP column of activity table is to small for IPv6 client address

### ISSUE THREAD

**Issue by bikerunner** [Thricehappy/EveScoutRescue#47]
Problem:
IPv6 addresses does not fit into activity.IP column. The current length of the IP column is 25 chars. The readable format of a full IPv6 address requires 39 chars (8*4 + 7 separators). The column contains already truncated IPv6 address data.

Change:
Adjust the column length to 40 chars.
* affects DB structure docu (README.md)
* test and prepare a SQL statement to modify the life DB table
* apply the SQL statement to the live DB

**Comment by bikerunner** [comment]
This should work (tested on dev instance):
ALTER TABLE `activity` CHANGE COLUMN `ip` `ip` VARCHAR(40);

Do not forget a DB backup before apply.

**Comment by Thricehappy** [comment]
Fixed.
