### ISSUE TITLE
Support and use secure transport with HTTPS

### ISSUE THREAD

**Issue by bikerunner** [Thricehappy/EveScoutRescue#48]
It's a good pattern to support transport layer data protected using HTTPS. This is more important for account access token information for the eve account.

This may some steps (may be incomplete listed):
* acquire a SSL certificate (Let's encrypt provided free certificates with frequent renewal)
* enable HTTPS/secure support in web server
* check all links to use current protocol (or switch to https later)
* set the eve SSO login back link to https

The signal forum is already served with HTTPS. And a request for the Co-Pilot to support HTTPS was already made in forum. This is a mix of development (checks) and operation configuration.

Enabling HTTPS may increase the CPU load on the server slightly because of the encryption/decryption processing.

**Comment by Thricehappy** [comment]
I updated domain to use SSL today. Can you confirm it is working on your end? Once you confirm, I'll update the SSO back link accordingly. Thanks!

**Comment by bikerunner** [comment]
* auth-inc.php: $charimg link needs to be changes to https if enabled (same in to sample files)
* some of the external links may be changed later to https (not important for internal use)
* back link exists in auth-inc and login php files
