### ISSUE TITLE
Prevent same-day tends

### ISSUE THREAD

**Issue by Thricehappy** [Thricehappy/EveScoutRescue#59]
Pilots should not be able to tend a cache on the same day it was sowed or previously tended. A cache that has just been used in a rescue (i.e., adjunct) CAN be tended on same day, if needed.

**Comment by bikerunner** [comment]
How is "same day" defined?
* within 24 hours from last activity
* counts the date diff only ("1.1. 23:59" and "2.1. 00:01" are two days?)

Extension: Display the next valid tend date (and time).

Question: Are the times in the DB normalized to UTC (Eve Time)? Or is this current ESRC server time?

**Comment by Thricehappy** [comment]
"Same day" is within 24 hours from last activity.

Times in db are just local time, not UTC. We can change this, though, if it would make better sense.
