### ISSUE TITLE
Add "total active caches" counter to ESR home page

### ISSUE THREAD

**Issue by Thricehappy** [Thricehappy/EveScoutRescue#63]
It would be great to let the entire community know how many active caches are currently out in space on https://evescoutrescue.com/home/

**Comment by bikerunner** [comment]
Would it be sufficient to change the text in the following way:
"...  come across one of our rescue caches (x active) or an unpiloted rescue frigate. ..."
This would be a simple change.

Or is some extra styling necessary?

**Comment by Thricehappy** [comment]
I was thinking the number would be highlighted in some way, so that it was more apparent and easier to see, rather than just buried in the text. maybe it could be in that same top panel header, but pulled out to the right in its own little box or in different colored text?

I'm not a designer, just ideas.

**Comment by bikerunner** [comment]
T>he number of confirmed rescues should be displayed as well.
