### ISSUE TITLE
Better support for caches that are tended by locals

### ISSUE THREAD

**Issue by Thricehappy** [Thricehappy/EveScoutRescue#64]
We need a way to identify in the system a cache that is being tended by locals. In these cases, we need to know who is tending it, incl. corp name.

The expiration date for these caches should not be updated when the cache is tended, and they should be marked as basically never expiring. Status remains "Locals tend".

If a scout tends the cache and it cannot be located, they should be able to expire it as normal. Status of "Locals tend" goes away in this scenario. (That status is cache-specific, not system-specific.)

We also need to add the Anoikis Division holes to this list.

**Comment by bikerunner** [comment]
Should we add some functionallity:
* generate a unique cache tend ID for "local" managed caches
* a link with this ID is send to the responsible person of the corp (can be shared in corp)
* the corp calls this link each time the cache is tended -> we get the status of the cache
* we can expire the cache if the corp does not continue to tend the cache

Extra idea (may be related to copilot): Systems with an existing and local managed cache should be noted in copilot. A corp member can check if the cache still exists (dscan would be enought) if he enters the system. The cache may be marked as expired if not found (admin access required?) and the link becomes invalid.

Similar handling may be introduced to keep WH locked from sowing. The corp refreshes the lock with a unique link.

**Comment by Thricehappy** [comment]
I want to make it as easy as possible for non-Signal pilots to tend caches, so I thought it would be easiest if we don't require them to do any data entry at all. They can tend the cache, and we just assume it is being tended, and we set the expire date to some arbitrarily distant value so that the cache does not get auto-expired by the cron script.

The issue now is that when a Signal pilot tends one of these caches, it updates the expiration date to 30 days out, which, if I don't catch in time, results in that cache possibly expiring in our system when it is actually still out in space, being maintained by the locals.

If we can somehow flag those so that they can be tended without affecting the expiration date, I thought that would be best. And periodically, I can go in and check all of the "local tend" caches and push the dates out further if needed.

We should be able to expire them as usual, though, in situations when locals change, forget, leave, etc.

For the "no sow" systems, I do not want to automate the process of setting that up or renewing it. I am concerned that will be abused. If a corp wants to extend a "no sow" request in a given system, they need to contact us directly and we need to update the system accordingly.

**Comment by Thricehappy** [comment]
Let's use J110915 as our test case for this. It won't expire until May 24, so that gives us plenty of time to work on this.

**Comment by Thricehappy** [comment]
Tending by locals has been proven unpopular and probably not a great idea to promote. So, closing this out.
