### ISSUE TITLE
Allow the users to enter image links related to cache drive event

### ISSUE THREAD

**Issue by bikerunner** [Thricehappy/EveScoutRescue#76]
* show all actions for the current pilot (within a defined time frame)
* order display by time or system name
* allow to enter image links for each displayed action (do not check links)
* save/update links
* prevent editing after end of event +1day (no modification after review starts)
* provide a simple interface for admin to review and approve each action

**Comment by Thricehappy** [comment]
Should we go ahead and close this now that the event is over? Or do you still want to work on it for the next one?

**Comment by Thricehappy** [comment]
The imgur process used for this past event worked fine. I don't think this is needed for future cache drive events.
