### ISSUE TITLE
Fix handling on search history for original import records

### ISSUE THREAD

**Issue by Thricehappy** [Thricehappy/EveScoutRescue#84]
Records imported from the old system into the new database on Mar-18 have 'Sower' instead of "sower". This is not being handled correctly in the search history display.

Might want to tackle converting all "sower" to "Sower" while we're at it, at least for display.

**Comment by bikerunner** [comment]
I think the table definition of the activity table is slightly wrong:

     ActivityDate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

Why is the activity date updated if the data set is changed? The activity date does not depend on the update operation I think. (Relates to #92 )

**Comment by bikerunner** [comment]
This sql statement may fix the issue:

    update activity set ActivityDate = ActivityDate, EntryType = 'sower' where entryType = 'Sower';

The 'activitydate' value should not use the default update action as a value is set. Please test careful to not modify the activity date on update.

**Comment by Thricehappy** [comment]
ActivityDate updating was changed with #82, so that is no longer an issue.

search page updated to handle "Sower" case. Good enough for now.
