### ISSUE TITLE
Change sort order of Notes on search page

### ISSUE THREAD

**Issue by Thricehappy** [Thricehappy/EveScoutRescue#91]
I would like for notes to use same order as History (newest first).

**Comment by bikerunner** [comment]
This can be done for new notes only currently and result in a display mix. The notes are manually appended on action creation.

Or this issue can only be solved with issue #92 .

What is your preferred solution?

**Comment by Thricehappy** [comment]
Let's just leave it for now and deal with this as part of #92. Thanks.

I will close this issue and add a relevant note to #92.
