### ISSUE TITLE
DB Restructure

### ISSUE THREAD

**Issue by Thricehappy** [Thricehappy/EveScoutRescue#92]
The database needs restructured. This will be a big project since it will affect everything. List of things to make sure get optimized:

* linkage between activity and cache tables needs to be much tighter
* notes should be in its own table (notes should have same sort order as History [newest first])
* pilots table?

**Comment by bikerunner** [comment]
I think a pilots table may be overhead. It need to be managed somehow. This may be an optional topic later I think.

Does a cache need separate notes? It's almost a combined copy of the activity notes currently.

**Comment by Thricehappy** [comment]
I'm not sure about a Pilots table, either. Just wanted to note it.
Once activity and cache tables are linked better, activity notes may suffice, yes.

**Comment by bikerunner** [comment]
Most of the text columns is currently treated as case insensitive. This should be changed to be case sensitive. This may help to find different usage of upper and lower case values.

**Comment by adeadparrot** [comment]
I was going to close this as I thought it was done, but what is the open issue with cache notes? can we close this one and reopen a separate issue for cache notes, if it is indeed still an issue

**Comment by Thricehappy** [comment]
I do not think there is still an issue with cache notes, but that may be one for @chigaze to comment on.

**Comment by Thricehappy** [comment]
No further comment from anyone on this, so closing for now.
